### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by ghost** [JasonTheAdams/PiklistHelper#1]
Hello there,
I've been struggling with an issue with validation these past days and since it might also affect PiklistHelper, I thought you might be able to help me.

Originally, I was trying to add custom validation rules but couldn't make them work (validation always pass). Worst, my custom validation breaks some core PikList validation rule (the e-mail one, for instance).
When I searched a bit more, I realized PiklistHelper had the same effect. If I comment out PiklistHelper, the e-mail validation work again.

I ask the question on Piklist forum but no luck so far:
https://piklist.com/support/topic/validation-always-pass/#post-3261

I'd like to know if I'm the only one having this issue? 
I tested on a fresh install of WP with a barebone plugin. I just added a Piklist custom settings with one box, and tried to use PiklistHelper zip-code validation. It always passes. What's more, the e-mail validation (a core validation in Piklist) always passes too.
Any custom validation rule I add had the same effect.

Any help would be very welcome!

**Comment by JasonTheAdams** [comment]
Greetings @AngeliqueVille!

Thanks for making an issue for the problem. Helps me to make sure I get it. I just fixed on the master branch (ec5d4219a8a). First, as you saw on the forums, the validations hook passed the pre-existing rules, and new rules needed to be merged and returned. Second, the arguments for validation callbacks changed, breaking all the existing validations that used callbacks.

If you have any further issues with the zip-code validation, please give me an example zip-code that you're inputting that I can test against.

Thanks!

**Comment by ghost** [comment]
It works perfect now. Thank you very much for your (super fast) help.
