### ISSUE TITLE
Date-range validation

### ISSUE THREAD

**Issue by ghost** [JasonTheAdams/PiklistHelper#3]
Hello!
I'm afraid I'm coming with a validation issue (again). Might be my fault though: I'm not too sure if I'm creating the right piklist form to use with PiklistHelper "date-range" validation.

Here is what I wrote: 

``` php
piklist('field', array(
    'type' => 'group'
    ,'field' => 'event_dates'
    ,'columns' => '12'
    ,'label' => __('Event Schedule') 
    ,'add_more' => false
    ,'fields' => array(
        array(
             'type' => 'datepicker'
            ,'field' => 'start-date'
            ,'columns' => 6
            ,'label' => __('Start')
            ,'attributes' => array(
            'class' => 'text'
            )
            ,'options' => array(
                'dateFormat' => 'M d, yy'
                ,'firstDay' => '0'
                )
                )
            ,array(
                'type' => 'datepicker'
                ,'field' => 'end-date'
                ,'columns' => 6  
                ,'label' => __('End')
                ,'attributes' => array(
                    'class' => 'text'
                )
                ,'options' => array(
                    'dateFormat' => 'M d, yy'
                    ,'firstDay' => '0'
                    )
            )   
        )
    ,'validate' => array (
        array(
        'type' => 'date-range'
        )
    )                      
));
```

Validation always passes. :(
Could you help me with this? Thank you :)

**Comment by JasonTheAdams** [comment]
Hi @AngeliqueVille!

This field hasn't been updated to the latest piklist arguments. Do me a favor and change line 260 of the class to: `public static function check_date_range($index, $values, $options, $field, $fields) {` and let me know if that fixes the issue.

**Comment by JasonTheAdams** [comment]
I just started a pull request #4 to get this issue resolved.

**Comment by JasonTheAdams** [comment]
@AngeliqueVille I ended up having to ditch the pull request after the recent update of PiklistHelper to a plugin. Please let me know if the fix I suggested here solved the problem.
